### ISSUE TITLE
How one can get URL of uploaded file?

### ISSUE THREAD

**Issue by ps6067966** [Lukiya/flutter_onedrive#1]

**Comment by Lukiya** [comment]
This tool is using personal token, which means files are protected, you have to share that file to get a url.
Or you can use token to call API to set it to public, see 

[https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online)
