### ISSUE TITLE
Webview does not close automatically after logging in to microsoft account

### ISSUE THREAD

**Issue by ayaanpathan** [Lukiya/flutter_onedrive#2]
Hi, 

Thank you for this package. 

I am facing an issue where the webview does not close automatically after logging in. It gets stuck and no action is happening on clicking 'Continue' or 'Cancel'

**Comment by Lukiya** [comment]
Sounds like you didn't register the right callback schema.
Please refer to:
[https://pub.dev/packages/url_launcher](https://pub.dev/packages/url_launcher)

# Android
    <activity android:name="com.linusu.flutter_web_auth.CallbackActivity">
      <intent-filter android:label="flutter_web_auth">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="YOUR_CALLBACK_SCHEMA" android:host="auth" />
      </intent-filter>
    </activity>
	
# iOS
	    <key>CFBundleURLTypes</key>
		<array>
			<dict>
				<key>CFBundleTypeRole</key>
				<string>Editor</string>
				<key>CFBundleURLName</key>
				<string>auth</string>
				<key>CFBundleURLSchemes</key>
				<array>
					<string>YOUR_CALLBACK_SCHEMA</string>
				</array>
			</dict>
		</array>
