### ISSUE TITLE
How do I check if the user has a valid authorised token?

### ISSUE THREAD

**Issue by ayaanpathan** [Lukiya/flutter_onedrive#3]
Hi, 

as the title states, how do I check if the user is already logged in and their token is valid or not? I don't want the user to login everytime they try to upload a file to their drive.

**Comment by Lukiya** [comment]
After you call await onedrive.connect(); url_launcher will redirect your user to microsoft login page. if user login success, it will redirect user to the callback schema you specified, and if you register that callback schema right, your app will be open, and token will be saved automatically into secure storage.

**Comment by ayaanpathan** [comment]
That I understood and that's working fine as expected. I am asking how do I make sure that the token is valid without signing in again as I don't want the user to login each time before uploading a file.

**Comment by Lukiya** [comment]
As long as user doesn't revoke it and refresh token is not expired, it will refresh automatically after access token expired.

**Comment by ayaanpathan** [comment]
Yes, but is there any way to check that before calling onedrive.connect() ?

**Comment by Lukiya** [comment]
> Yes, but is there any way to check that before calling onedrive.connect() ?

There is a method: onedrive.isConnected(), use this with FutureBuilder to check whether access token has been saved.
