### ISSUE TITLE
How to setup manifest for /common/oauth2/v2.0/authorize

### ISSUE THREAD

**Issue by longleeproduction** [Lukiya/flutter_onedrive#4]
I have face problem same issues https://github.com/dotnet/AspNetCore.Docs/issues/19795, when change from /common/oauth2/v2.0/authorize to /consumers/oauth2/v2.0/authorize api call success.
My app setting  "signInAudience": "PersonalMicrosoftAccount",
Please advise me.

**Comment by Lukiya** [comment]
I have no idea of what that issue means, read below document, follow directions in it.
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online
and
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online

**Comment by longleeproduction** [comment]
I found my problem.
When create new application select supported account type: Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox) 
or edit manifest: "signInAudience": "AzureADandPersonalMicrosoftAccount",
