### ISSUE TITLE
Problem with authorization

### ISSUE THREAD

**Issue by Space647** [Lukiya/flutter_onedrive#5]
Hello [Lukiya](https://github.com/Lukiya), i found one problem with your library. For authorization need client_secret. Add for conctruction please.

  OneDrive({
    required this.clientID,
    required this.redirectURL,
    required this.clientSecret,
    this.scopes = "offline_access Files.ReadWrite.All",
    this.state = "OneDriveState",
    ITokenManager? tokenManager,
  }
  
        final result = await OAuthWebScreen.start(
        context: context,
        authorizationEndpointUrl: authEndpoint,
        tokenEndpointUrl: tokenEndpoint,
        clientSecret: clientSecret,
        clientId: clientID,
        redirectUrl: redirectURL,
        scopes: scopeArray,

        onCertificateValidate: (certificate) {

          return true;
        },

      );

**Comment by Lukiya** [comment]
According to: 
https://learn.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online

"_For public client apps (native apps or JavaScript apps), you do not need to an app password._"

It's not safe to include client secret in your app. Follow above article to register an app without secret.
