### ISSUE TITLE
Web Supoort, correct the pub.dev page.

### ISSUE THREAD

**Issue by kaushikcw** [Lukiya/flutter_onedrive#6]
Hi @Lukiya ,

I see that your package supports web. All the dependenices that you use support the web as well. Can you please update the pub.dev page to reflect that:

https://pub.dev/packages/flutter_onedrive

**Comment by Lukiya** [comment]
Unfortunately, it deepened on below dependence: 

package:flutter_onedrive/flutter_onedrive.dart that imports:
package:oauth_webauth/oauth_webauth.dart that imports:
package:oauth_webauth/src/base_web_view.dart that imports:
package:flutter_inappwebview/flutter_inappwebview.dart **_that declares support for platforms: Android, iOS._**
