### ISSUE TITLE
Class 'AuthorizationException' has no instance getter 'expiration'.

### ISSUE THREAD

**Issue by Alvish0407** [Lukiya/flutter_onedrive#7]
<img width="1636" alt="Screenshot 2023-05-17 at 7 09 54 PM" src="https://github.com/Lukiya/flutter_onedrive/assets/80829856/ea5b5915-77c3-49c6-a23a-e4dddccb6680">

```
I/flutter (11649): # DefaultTokenManager -> _saveTokenMap: NoSuchMethodError: Class 'AuthorizationException' has no instance getter 'expiration'.
I/flutter (11649): Receiver: Instance of 'AuthorizationException'
I/flutter (11649): Tried calling: expiration
```

**Comment by Alvish0407** [comment]
Based on my understanding of the code, it appears that error handling is not implemented or not sufficiently effective.

`OAuth authorization error (invalid_request): The%20request%20is%20not%20valid%20for%20the%20application%27s%20%27userAudience%27%20configuration.%20In%20order%20to%20use%20/common/%20endpoint%2C%20the%20application%20must%20not%20be%20configured%20with%20%27Consumer%27%20as%20the%20user%20audience.%20The%20userAudience%20should%20be%20configured%20with%20%27All%27%20to%20use%20/common/%20endpoint..`

Despite receiving a successful response, [I encountered an error](https://github.com/Lukiya/flutter_onedrive/issues/7#issue-1713957203)

**Comment by Lukiya** [comment]
[c10cf02](https://github.com/Lukiya/flutter_onedrive/commit/c10cf0276a6ebcb0c3415d079289814aaae6f457)
